# filepath: /Users/2110184/IdeaProjects/pillar/src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pillardb # Matches docker-compose DB name
    username: pillaruser                         # Matches docker-compose user
    password: pillarpassword                     # Matches docker-compose password (use your chosen password)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates/updates schema automatically on startup (good for dev)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Optional: logs SQL statements
    properties:
      hibernate:
        format_sql: true # Optional: formats logged SQL
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jackson:
    time-zone: ${TIMEZONE}
#  mail:
#      host: ${MAIL_HOST}
#      port: ${MAIL_PORT}
#      username: ${MAIL_USERNAME}
#      password: ${MAIL_PASSWORD}
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true
server:
  servlet:
    context-path: /api