spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pillar
    username: postgres
    password: 2210
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
            show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: UTC  # Set a fixed timezone instead of using ${TIMEZONE}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  health:
    redis:
      enabled: false

 # Make sure all endpoints are under /api