# filepath: /Users/2110184/IdeaProjects/pillar/src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:h2:mem:pillardb # Changed back to in-memory mode
    driver-class-name: org.h2.Driver
    username: sa
    password: # Keep password empty or remove the line if you prefer
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false # Keep false for security unless needed
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jackson:
    time-zone: ${TIMEZONE}
  mail:
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
server:
  servlet:
    context-path: /api