spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pillar
    username: root
    password: 22102003
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: UTC  # Set a fixed timezone instead of using ${TIMEZONE}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  health:
    redis:
      enabled: false
server:
  servlet:
    context-path: /api